Feat/create a task
KivancUlucan/Capstone-Project pull request #7
Opened 2023-05-12 09:34 UTC by KivancUlucan

2023-05-12 14:46 UTC, doctype-Melvin requested changes
Hi Kivanc!

You're doing great. 

I left a couple suggestions for you to consider when revising your code. Keep it DRY (don't repeat yourself) would be my biggest tip.

Keep it going!

2023-05-12 14:53 UTC, doctype-Melvin requested changes
Hi Kivanc,

I've left you some suggestions for your code revision. You could make your life easier if you keep your code DRY (don't repeat yourself). 

Other than that, you're doing great! Keep it going!

2023-05-12 14:53 UTC, doctype-Melvin commented on pages/addTask.js
> +`;
```suggestion
const StyledLabel = styled.label`
  display: flex;
  flex-direction: column;
  font-size: 0.8rem;
  margin-bottom: 0.2rem;
`;
```

2023-05-12 14:53 UTC, doctype-Melvin commented on pages/addTask.js
> +`;
```suggestion
const StyledInput = styled.input`
  border: 0.03rem solid #d1d1d1;
  border-radius: 0.3rem;
  width: 20rem;
  height: 2.5rem;
  outline: none;
  padding: 0.5rem 1rem;
  margin-bottom: 1rem;
`;
```

2023-05-12 14:53 UTC, doctype-Melvin commented on pages/addTask.js
> +const LabelForDescription = styled.label`
```suggestion
const StyledLabel = styled.label`
```

2023-05-12 14:53 UTC, doctype-Melvin commented on pages/addTask.js
> +const LabelForPriority = styled.label`
```suggestion
const StyledLabel = styled.label`
```

2023-05-12 14:53 UTC, doctype-Melvin commented on pages/addTask.js
> +const LabelForCategory = styled.label`
```suggestion
const StyledLabel = styled.label`
```

2023-05-12 14:53 UTC, doctype-Melvin commented on pages/addTask.js
> +`;
This has the same styling rules as SelectForCategory. StyledSelect would make sense here.

2023-05-15 09:59 UTC, djfarly requested changes
Hej Kivancm

thank you for the PR!

I only have one slightly larger comment (the one about adding an `id`), otherwise this looks very good to me!

Cheers, Jan

2023-05-15 09:59 UTC, djfarly commented on components/TaskCard/TaskCard.js
> +      <Description>Description:{task.description} </Description>
misaligned space
```suggestion
      <Description>Description: {task.description}</Description>
```

2023-05-15 09:59 UTC, djfarly commented on pages/board.js
> +          <TaskCard key={task.title} task={task} />
the task title might not be the best candidate for `key`. Keys have to be unique per list, so if you have two tasks with the same title React will rightfully complain.

Consider adding an `id` to your tasks to have a unique identifier.

To do so install `uid`

```
npm i uid
```

and then change your `handleAddTask` function in `_app.js` to create ids:

```js
import { uid } from "uid";

/* … */

  function handleAddTask(newTask) {
    setTasks([...tasks, {...newTask, id: uid()}]);
  }
```

then you can do:
```suggestion
          <TaskCard key={task.id} task={task} />
```

2023-05-15 09:59 UTC, djfarly commented on pages/board.js
> +    <>
you do not need this fragment

2023-05-15 09:59 UTC, djfarly commented on pages/board.js
> +  console.log(tasks);
try not to merge debug console.logs

```suggestion
```

2023-05-15 12:08 UTC, djfarly approved these changes
👍 lgtm!

2023-05-16 07:29 UTC, merged